using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Assets.Scripts.App.Data_Management.Handshakes {
    public static class HandshakeProtocolCertificate {

        private static bool _initialized = false;
        private static readonly string[] Certificates = {
            @"-----BEGIN CERTIFICATE-----
MIIGdDCCBVygAwIBAgIQfjnaE27zvrw19ScXLmqj8DANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE3MTEyMjAwMDAwMFoX
DTE5MDIyMTIzNTk1OVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3Ju
aWExEjAQBgNVBAcMCVBhbG8gQWx0bzEVMBMGA1UECgwMVk13YXJlLCBJbmMuMRYw
FAYDVQQLDA1JVCBPcGVyYXRpb25zMRUwEwYDVQQDDAwqLnZtd2FyZS5jb20wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpKMSSDAV6MTquamPCZmLmqGx6
8qA45amcwnqDr4yhMWSiKFhfemeS8oi0Co+24vt6leVkUKyXtbf7CadLQFkm25ke
duIAVS1EwqaSnNHNTYFs0I1TiVrQXtdQDlFRPzHACkcYjJqcZcsvrAZPZlrFgLTS
yW44gEYOqm/RcnD6UMDHnhrsKNjl9zJ8UHMNGZNRoZifxHePZ7Pc66H/uIHWXhOH
ZlJuv3EvtLLNPCgZb8LU6B79JuJkheVAi5z77GhTyBXFW5JWhfwrN/jdCLODrd/l
sDmjJ3c0EXvqE+GuH02zdaVG8kbeYlRONaBQqPpLqEMBqr86X9cmW1FBh+gzAgMB
AAGjggLuMIIC6jAjBgNVHREEHDAaggwqLnZtd2FyZS5jb22CCnZtd2FyZS5jb20w
CQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCBaAwYQYDVR0gBFowWDBWBgZngQwBAgIw
TDAjBggrBgEFBQcCARYXaHR0cHM6Ly9kLnN5bWNiLmNvbS9jcHMwJQYIKwYBBQUH
AgIwGQwXaHR0cHM6Ly9kLnN5bWNiLmNvbS9ycGEwKwYDVR0fBCQwIjAgoB6gHIYa
aHR0cDovL3NzLnN5bWNiLmNvbS9zcy5jcmwwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
CCsGAQUFBwMCMB8GA1UdIwQYMBaAFF9gz2GQVd+EQxSKYCqy9Xr0QxjvMFcGCCsG
AQUFBwEBBEswSTAfBggrBgEFBQcwAYYTaHR0cDovL3NzLnN5bWNkLmNvbTAmBggr
BgEFBQcwAoYaaHR0cDovL3NzLnN5bWNiLmNvbS9zcy5jcnQwggF9BgorBgEEAdZ5
AgQCBIIBbQSCAWkBZwB1AN3rHSt6DU+mIIuBrYFocH4ujp0B1VyIjT0RxM227L7M
AAABX+EKzDcAAAQDAEYwRAIgJ2/9aCBADoU2JcR8AIvMED1UOHmEmGVWPMfmMqpb
g5oCID04Sa0DTuN/hhGvJDfElUtODvrrSwtfBlIo1eBZIQ1kAHcApLkJkLQYWBSH
uxOizGdwCjw1mAT5G9+443fNDsgN3BAAAAFf4QrMbgAABAMASDBGAiEA3/Br7WBb
Qz/w5w5FkO2KDSB8jMQtQf7Jms6fFmbOBAECIQCtGCyDE64BlPZYibaBPru9uzT9
6G3rwEVukuXArPPimwB1AO5Lvbd1zmC64UJpH6vhnmajD35fsHLYgwDEe4l6qP3L
AAABX+EKzjEAAAQDAEYwRAIgNkORxXWzEx+EM4pIGisW6jwk9st2cnOFXtA9h9mg
sFcCIHphvwStyrQ58rzgK6WiKd8QiNh35Nz/9L0DY9Vy7Nk3MA0GCSqGSIb3DQEB
CwUAA4IBAQAOM80Z15d7SLCmMgpEEiHN/0fQLEDydP4KRLlAlls0F2C1HcN070r/
moahK3DdItBibXIY9h0DRLi0j+czwpbwak9NnzcPecrBX+yZRnA44bsc8VbCzREh
gDuEavDNnCTEHZ4EO9DRo83fD5iwqx/ATgy9eiOMfQL5NggbTfeKlJQ5DF4Ihv4Z
uMIc6ffUkAXho/yHmv0KA+Z4nfXxR9upBIpzXIfmf5LMjYXQnqV/Vit7cjxHXDQl
rOzCl0Yfuzx7e8aqahwC30L3BZVdt4cr6tMQS84FydrJo/GfxnuIWvU2/IPAbnNI
qMQf/OOc/Rdkz1f5FLFSgnKsTHq76GaE
-----END CERTIFICATE-----"
        };

        public static void Initalize() {
            if (_initialized) return;
            _initialized = true;
            foreach(var c in Certificates)
                AndroidHttpsHelper.AddCertificate(c);
        }
    }
}
